server:
  port: 8084

spring:
  application:
    name: group

  grpc:
    server:
      port: 9094
    image:
      address: ${GRPC_IMAGE_URL:localhost:9092}
    user:
      address: ${GRPC_USER_URL:localhost:9091}

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update

springdoc:
  swagger-ui:
    path: /groups/swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /groups/v3/api-docs

logging:
  level:
    flipnote.group: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true
