server:
  port: 8084

spring:
  application:
    name: group

  grpc:
    server:
      port: 9094
    image:
      address: ${GRPC_IMAGE_URL:localhost:9092}

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update

springdoc:
  swagger-ui:
    path: /groups/swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /groups/v3/api-docs


image-clean:
  batch-size: 300
  orphan-grace-minutes: 10

image:
  default:
    user: https://flipnote-bucket.s3.ap-northeast-2.amazonaws.com/image/default/user.png
    group: https://flipnote-bucket.s3.ap-northeast-2.amazonaws.com/image/default/group.png
    cardSet: https://flipnote-bucket.s3.ap-northeast-2.amazonaws.com/image/default/cardset.png

logging:
  level:
    flipnote.group: DEBUG
